export const ENV_KEYS = {
  DATABASE_PATH: 'DATABASE_PATH',
  DATABASE_URL: 'DATABASE_URL',
  HONEYPOT_SECRET: 'HONEYPOT_SECRET',
  NODE_ENV: 'NODE_ENV',
  SESSION_SECRET: 'SESSION_SECRET',
} as const
