export const ENV_KEYS = {
  BASE_URL: 'BASE_URL',
  DATABASE_PATH: 'DATABASE_PATH',
  DATABASE_URL: 'DATABASE_URL',
  HONEYPOT_SECRET: 'HONEYPOT_SECRET',
  IMAGE_STORE_PATH: 'IMAGE_STORE_PATH',
  NODE_ENV: 'NODE_ENV',
  SESSION_SECRET: 'SESSION_SECRET',
} as const
