export const ENV_KEYS = {
  NODE_ENV: "NODE_ENV",
  DATABASE_PATH: "DATABASE_PATH",
  DATABASE_URL: "DATABASE_URL",
  SESSION_SECRET: "SESSION_SECRET",
  HONEYPOT_SECRET: "HONEYPOT_SECRET",
} as const
