# fly.toml app configuration
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cz-vednemesicnik'
primary_region = 'fra'

[build]
  dockerfile = '/docker/Dockerfile'
  ignorefile = '/docker/.dockerignore'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
