# fly.toml app configuration file generated for cz-vednemesicnik on 2025-01-31T14:21:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cz-vednemesicnik'
primary_region = 'fra'

[build]
  dockerfile = '/docker/fly/Dockerfile'
  ignorefile = '.dockerignore'

[env]
  BASE_URL = 'https://vednemesicnik.cz'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
