export const FORM_CONFIG = {
  authenticityToken: {
    name: 'csrf',
  },
  intent: {
    name: 'intent',
    value: {
      archive: 'archive',
      bulkDelete: 'bulk-delete',
      changePublishedAt: 'change-published-at',
      createFilter: 'create-filter',
      delete: 'delete',
      deleteFilter: 'delete-filter',
      deleteImage: 'delete-image',
      overwriteFilter: 'overwrite-filter',
      publish: 'publish',
      regenerateBackupCodes: 'regenerate-backup-codes',
      renameFilter: 'rename-filter',
      restore: 'restore',
      retract: 'retract',
      review: 'review',
      setDefaultFilter: 'set-default-filter',
      signInWithBiometric: 'sign-in-with-biometric',
      signOut: 'sign-out',
      startEnrollment: 'start-enrollment',
      toggleSharedFilter: 'toggle-shared-filter',
      unsetDefaultFilter: 'unset-default-filter',
      updateProfile: 'update-profile',
      uploadImage: 'upload-image',
    },
  },
  redirect: {
    name: 'redirect',
  },
} as const
