name: vdm_app

services:
  app:
    image: vdm_app_image
    container_name: vdm_app_container
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data:
    name: vdm_app_data
